name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install .sh
      run: $(pwd)/.github/workflows/github.install.sh

    - name: Build Docker Image
      run: docker build . --tag my-image-name:$(date +%s)
