name: Build Docker Image

language: go
go:
 - 1.11.x
 - 1.12.x
 - 1.13.x
 - master

addons:
  apt:
    packages:
      libpcap-dev

# use modules except for older versions (see below)
install: true

env:
  - GO111MODULE=on


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --tag my-image-name:$(date +%s)
